#!/bin/bash

#
# Use docker to run keycloak on the remote server.
#

ANSIBLE_PLAYBOOK=$(which ansible-playbook)
export ANSIBLE_HOST_KEY_CHECKING=False

IP_ADDRESS=$(terraform output keycloak_public_ip)
KEYCLOAK_ADMIN_USERNAME=$(terraform output keycloak_admin_username)
KEYCLOAK_ADMIN_PASSWORD=$(terraform output keycloak_admin_password)
PKI_PRIVATE_KEY=$(terraform output pki_private_key)
SSH_USER=$(terraform output ssh_user)

python3 \
  $ANSIBLE_PLAYBOOK \
  -v \
  --extra-vars "keycloak_admin_username=$KEYCLOAK_ADMIN_USERNAME" \
  --extra-vars "keycloak_admin_password=$KEYCLOAK_ADMIN_PASSWORD" \
  --extra-vars "ssh_user=$SSH_USER" \
  -i "$IP_ADDRESS," \
  --private-key $PKI_PRIVATE_KEY \
  -u $SSH_USER \
  playbook.keycloak.yml
