#!/bin/bash

#
# This script uses a docker container to send commands to the
# keycloak server. The docker container is used so that keycloak
# does not need to be installed locally.
#

LOG_FILE=$(basename $0).log
exec > >(tee ${LOG_FILE}) 2>&1

type docker
if [ $? != 0 ]; then
  echo "Please install 'docker'."
  exit 1
fi

type jq
if [ $? != 0 ]; then
  echo "Please install 'jq'."
  exit 1
fi

#
# INPUT VALIDATION
#
if [ -z $K8S_DOMAIN_NAME ]; then
    echo "Missing Environment Variable: K8S_DOMAIN_NAME"
    exit 1
fi

IP_ADDRESS=$(terraform output keycloak_public_ip)
KEYCLOAK_ADMIN_USERNAME=$(terraform output keycloak_admin_username)
KEYCLOAK_ADMIN_PASSWORD=$(terraform output keycloak_admin_password)
KEYCLOAK_REALM=$(terraform output keycloak_realm)
KEYCLOAK_REALM_ADMIN_USERNAME=$(terraform output keycloak_realm_admin_username)
KEYCLOAK_REALM_ADMIN_PASSWORD=$(terraform output keycloak_realm_admin_password)
KEYCLOAK_REALM_DEVELOPER_USERNAME=$(terraform output keycloak_realm_developer_username)
KEYCLOAK_REALM_DEVELOPER_PASSWORD=$(terraform output keycloak_realm_developer_password)
KEYCLOAK_REALM_VISITOR_USERNAME=$(terraform output keycloak_realm_visitor_username)
KEYCLOAK_REALM_VISITOR_PASSWORD=$(terraform output keycloak_realm_visitor_password)
KEYCLOAK_CLIENT=$(terraform output keycloak_client)
KEYCLOAK_CLIENT_BASE_URL=$(terraform output keycloak_client_base_url)

KEYCLOAK_SUBDOMAIN_NAME=${KEYCLOAK_SUBDOMAIN_NAME:-"keycloak"}
FQDN="$KEYCLOAK_SUBDOMAIN_NAME.$K8S_DOMAIN_NAME"

#
# Authentication is not needed because the username and password 
# are sent on each request.
#

echo "Creating Realm: kubernetes"

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 create realms \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --set realm=$KEYCLOAK_REALM \
    --set enabled=true


echo "Creating the Password Policy (12 digits, 2 upper, 2 lower, 2 number, 2 special character)."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 update realms/$KEYCLOAK_REALM \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --set 'passwordPolicy="hashIterations(27500) and specialChars(2) and upperCase(2) and digits(2) and notUsername(undefined) and length(12)"'


echo "Creating roles."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 create roles \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --set name=administrator

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 create roles \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --set name=developer

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 create roles \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --set name=visitor


echo "Creating client."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 create clients \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --set enabled=true \
    --set clientId=$KEYCLOAK_CLIENT \
    --set publicClient=true \
    --set 'webOrigins=["*"]' \
    --set 'redirectUris=["/"]' \
    --set "rootUrl=$KEYCLOAK_CLIENT_BASE_URL"


echo "Getting the client id."

RESPONSE=$(docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 get clients \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    -q clientId=$KEYCLOAK_CLIENT)

#
# The sed and cut elements of the pipe below remove the 
# 'Logging into message' from the server.
#
CLIENT_ID=$(echo $RESPONSE | sed 's/\r/\n/g' | grep -v Logging | jq --raw-output '.[0].id')


echo "Creating protocol mapper."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 create clients/$CLIENT_ID/protocol-mappers/models \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --set name=roles \
    --set protocol=openid-connect \
    --set protocolMapper=oidc-usermodel-realm-role-mapper \
    --set 'config."id.token.claim"=true' \
    --set 'config."claim.name"=roles' \
    --set 'config."jsonType.label"=String' \
    --set 'config."multivalued"=true' \
    --set 'config."userinfo.token.claim"=true' \
    --set 'config."access.token.claim"=true'

echo "Turn off HTTPS requirement for realm."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 update realms/$KEYCLOAK_REALM \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --set 'sslRequired=none'

# .########..########....###....##.......##.....##.......###....########..##.....##.####.##....##
# .##.....##.##.........##.##...##.......###...###......##.##...##.....##.###...###..##..###...##
# .##.....##.##........##...##..##.......####.####.....##...##..##.....##.####.####..##..####..##
# .########..######...##.....##.##.......##.###.##....##.....##.##.....##.##.###.##..##..##.##.##
# .##...##...##.......#########.##.......##.....##....#########.##.....##.##.....##..##..##..####
# .##....##..##.......##.....##.##.......##.....##....##.....##.##.....##.##.....##..##..##...###
# .##.....##.########.##.....##.########.##.....##....##.....##.########..##.....##.####.##....##


echo "Creating the realm administrator account."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 create users \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --set username=$KEYCLOAK_REALM_ADMIN_USERNAME \
    --set enabled=true \
    --set 'requiredActions=[]'

echo "Setting the realm administrator password."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 set-password \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --username $KEYCLOAK_REALM_ADMIN_USERNAME \
    --new-password $KEYCLOAK_REALM_ADMIN_PASSWORD

echo "Assigning administrator role to administrator account."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 add-roles \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --uusername $KEYCLOAK_REALM_ADMIN_USERNAME \
    --rolename administrator


# .########..########....###....##.......##.....##....########..########.##.....##
# .##.....##.##.........##.##...##.......###...###....##.....##.##.......##.....##
# .##.....##.##........##...##..##.......####.####....##.....##.##.......##.....##
# .########..######...##.....##.##.......##.###.##....##.....##.######...##.....##
# .##...##...##.......#########.##.......##.....##....##.....##.##........##...##.
# .##....##..##.......##.....##.##.......##.....##....##.....##.##.........##.##..
# .##.....##.########.##.....##.########.##.....##....########..########....###...

echo "Creating the realm developer account."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 create users \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --set username=$KEYCLOAK_REALM_DEVELOPER_USERNAME \
    --set enabled=true \
    --set 'requiredActions=[]'

echo "Setting the realm developer password."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 set-password \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --username $KEYCLOAK_REALM_DEVELOPER_USERNAME \
    --new-password $KEYCLOAK_REALM_DEVELOPER_PASSWORD

echo "Assigning developer role to developer account."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 add-roles \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --uusername $KEYCLOAK_REALM_DEVELOPER_USERNAME \
    --rolename developer

# .########..########....###....##.......##.....##....##.....##.####..######..####.########..#######..########.
# .##.....##.##.........##.##...##.......###...###....##.....##..##..##....##..##.....##....##.....##.##.....##
# .##.....##.##........##...##..##.......####.####....##.....##..##..##........##.....##....##.....##.##.....##
# .########..######...##.....##.##.......##.###.##....##.....##..##...######...##.....##....##.....##.########.
# .##...##...##.......#########.##.......##.....##.....##...##...##........##..##.....##....##.....##.##...##..
# .##....##..##.......##.....##.##.......##.....##......##.##....##..##....##..##.....##....##.....##.##....##.
# .##.....##.########.##.....##.########.##.....##.......###....####..######..####....##.....#######..##.....##

echo "Creating the realm visitor account."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 create users \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --set username=$KEYCLOAK_REALM_VISITOR_USERNAME \
    --set enabled=true \
    --set 'requiredActions=[]'

echo "Setting the realm visitor password."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 set-password \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --username $KEYCLOAK_REALM_VISITOR_USERNAME \
    --new-password $KEYCLOAK_REALM_VISITOR_PASSWORD

echo "Assigning visitor role to visitor account."

docker run \
  --name keycloak-command \
  -it --rm \
  --entrypoint /opt/jboss/keycloak/bin/kcadm.sh \
  quay.io/keycloak/keycloak:11.0.3 add-roles \
    --no-config \
    --server https://$FQDN:8443/auth \
    --user $KEYCLOAK_ADMIN_USERNAME \
    --password $KEYCLOAK_ADMIN_PASSWORD \
    --realm master \
    --target-realm $KEYCLOAK_REALM \
    --uusername $KEYCLOAK_REALM_VISITOR_USERNAME \
    --rolename visitor
